last_state=""

hyprctl_command() {
  timeout 2s hyprctl "$@"
}

external_active() {
  # A connected DRM cable does not mean the compositor has restored its output.
  # Ignore DPMS here: intentional idle blanking must not enable another panel.
  local monitors
  monitors=$(hyprctl_command -j monitors) || return 1
  jq -se 'length == 1 and (.[0] | any(.[];
    (.name | test("^(DP-|HDMI-A-)")) and
    .disabled == false and .width > 0 and .height > 0))' <<< "$monitors" >/dev/null
}

external_connected() {
  for status in /sys/class/drm/card*-DP-*/status /sys/class/drm/card*-HDMI-A-*/status; do
    [ -e "$status" ] || continue
    grep -q '^connected$' "$status" && return 0
  done
  return 1
}

custom_monitors_file="${XDG_CONFIG_HOME:-$HOME/.config}/hypr/monitors.lua"

custom_monitor_config_matches_state() {
  [ -f "$custom_monitors_file" ] || return 1
  grep -Eq '^[[:space:]]*hl\.monitor\(' "$custom_monitors_file" || return 1

  if external_connected; then
    # Respect saved nwg-displays external layouts; ignore stale internal-only configs.
    # Match external connector names only in the output field; otherwise eDP-1
    # is accidentally treated as a DP-* external output.
    grep -Eq '^[[:space:]]*hl\.monitor\(\{.*output[[:space:]]*=[[:space:]]*"((DP-|HDMI-A-)|desc:)' "$custom_monitors_file"
  else
    # A saved external-only layout usually contains `eDP-1, disabled = true`;
    # do not mistake that stale disabled rule for a usable internal layout.
    grep -E '^[[:space:]]*hl\.monitor\(\{.*output[[:space:]]*=[[:space:]]*"eDP-' "$custom_monitors_file" \
      | grep -Eqv 'disabled[[:space:]]*=[[:space:]]*true'
  fi
}

apply_state() {
  force="${1:-}"

  if external_connected && ! external_active; then
    # Keep a usable fallback while HDMI/DP is still returning after wake.
    # Periodic reconciliation below retries even if no further event arrives.
    state="recovering"
  elif custom_monitor_config_matches_state; then
    state="custom"
  elif external_connected; then
    state="external"
  else
    state="internal"
  fi
  [ "$force" = force ] || [ "$state" != "$last_state" ] || return 0

  # `hyprctl keyword` only supports the legacy config parser. Apply monitor
  # rules through the Lua API used by the active Hyprland configuration.
  case "$state" in
    custom)
      # Runtime fallback rules survive unplugging a display. Restore the saved
      # layout when returning to it, but not on every monitor event generated by
      # that restoration (which would create a feedback loop).
      if [ "$last_state" != custom ]; then
        hyprctl_command eval 'dofile((os.getenv("XDG_CONFIG_HOME") or (os.getenv("HOME") .. "/.config")) .. "/hypr/monitors.lua")' >/dev/null || return 0
      fi
      ;;
    external)
      hyprctl_command eval 'hl.monitor({ output = "", mode = "preferred", position = "auto", scale = @MONITOR_SCALE@ })' >/dev/null || return 0
      external_active || return 0
      hyprctl_command eval 'hl.monitor({ output = "eDP-1", disabled = true })' >/dev/null || return 0
      ;;
    internal|recovering)
      hyprctl_command eval 'hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = @MONITOR_SCALE@ })' >/dev/null || return 0
      ;;
  esac
  # Shelllist follows Quickshell.screens and rebuilds its bar surfaces after
  # output topology changes, so no panel process restart is required here.
  last_state="$state"
}

runtime_dir="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

find_socket() {
  if [ -n "${HYPRLAND_INSTANCE_SIGNATURE:-}" ]; then
    socket="$runtime_dir/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
    [ -S "$socket" ] && printf '%s\n' "$socket" && return 0
  fi

  for socket in "$runtime_dir"/hypr/*/.socket2.sock; do
    [ -S "$socket" ] && printf '%s\n' "$socket" && return 0
  done

  return 1
}

export_instance_from_socket() {
  instance="${1%/.socket2.sock}"
  export HYPRLAND_INSTANCE_SIGNATURE="${instance##*/}"
}

main() {
  while true; do
    while ! socket="$(find_socket)"; do
      sleep 1
    done

    export_instance_from_socket "$socket"
    last_state=""
    apply_state

    # A read timeout also reconciles missed wake/hotplug events. Keep state in
    # this shell, and do not reapply our own rules on the events they generate.
    monitor_events < <(socat -U - UNIX-CONNECT:"$socket")

    sleep 1
  done
}

monitor_events() {
  local event result
  while true; do
    if IFS= read -r -t 2 event; then
      case "$event" in
        configreloaded*) last_state=""; apply_state ;;
        monitoradded*|monitorremoved*) apply_state ;;
      esac
    else
      result=$?
      [ "$result" -gt 128 ] || break
      apply_state
    fi
  done
}

if [ "${HYPR_MONITOR_AUTO_LIB_ONLY:-0}" != 1 ]; then
  main
fi
