# nwg-displays 0.4.x only emits deprecated Hyprlang fragments. Run it against
# temporary files, translate every accepted change to native Lua, and atomically
# update the version-controlled modules required by hyprland.lua.

runtime_root="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}/nwg-displays-lua"
target_monitors="@MONITORS_LUA@"
target_workspaces="@WORKSPACES_LUA@"
target_monitors_tmp="$target_monitors.tmp.$$"
target_workspaces_tmp="$target_workspaces.tmp.$$"
nwg_pid=

mkdir -p "$runtime_root"
exec 9>"$runtime_root/instance.lock"
if ! flock -n 9; then
  printf 'nwg-displays-lua is already running.\n' >&2
  exit 0
fi

runtime_dir="$(mktemp -d "$runtime_root/run.XXXXXX")"
legacy_monitors="$runtime_dir/monitors.conf"
legacy_workspaces="$runtime_dir/workspaces.conf"

# Invoked by the EXIT trap.
# shellcheck disable=SC2329
cleanup() {
  status=$?
  trap - EXIT
  if [ -n "$nwg_pid" ] && kill -0 "$nwg_pid" 2>/dev/null; then
    kill "$nwg_pid" 2>/dev/null || true
    wait "$nwg_pid" 2>/dev/null || true
  fi
  rm -rf "$runtime_dir"
  rm -f "$target_monitors_tmp" "$target_workspaces_tmp" "$target_workspaces_tmp.with-header"
  exit "$status"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

: >"$legacy_monitors"
: >"$legacy_workspaces"

fingerprint() {
  sha256sum "$legacy_monitors" "$legacy_workspaces" 2>/dev/null || true
}

convert_monitors() {
  tmp="$target_monitors_tmp"

  if awk '
    function lua_string(value, escaped) {
      escaped = value
      gsub(/\\/, "\\\\", escaped)
      gsub(/"/, "\\\"", escaped)
      return "\"" escaped "\""
    }

    function remember(output) {
      if (!(output in seen)) {
        seen[output] = 1
        order[++count] = output
      }
    }

    /^[[:space:]]*monitor[[:space:]]*=/ {
      line = $0
      sub(/^[[:space:]]*monitor[[:space:]]*=[[:space:]]*/, "", line)
      fields_count = split(line, fields, ",")
      output = fields[1]
      remember(output)

      if (fields[2] == "disable") {
        disabled[output] = 1
        next
      }

      if (fields[2] == "transform") {
        transform[output] = fields[3]
        next
      }

      disabled[output] = 0
      mode[output] = fields[2]
      position[output] = fields[3]
      scale[output] = fields[4]

      for (i = 5; i <= fields_count; i += 2) {
        if (fields[i] == "mirror")
          mirror[output] = fields[i + 1]
        else if (fields[i] == "bitdepth")
          bitdepth[output] = fields[i + 1]
        else if (fields[i] == "transform")
          transform[output] = fields[i + 1]
      }
    }

    END {
      if (count == 0)
        exit 2

      print "-- Generated by nwg-displays-lua. Do not edit manually."
      for (i = 1; i <= count; i++) {
        output = order[i]
        printf "hl.monitor({ output = %s", lua_string(output)

        if (disabled[output]) {
          printf ", disabled = true"
        } else {
          printf ", mode = %s, position = %s", lua_string(mode[output]), lua_string(position[output])
          if (scale[output] ~ /^[0-9]+([.][0-9]+)?$/)
            printf ", scale = %s", scale[output]
          else
            printf ", scale = %s", lua_string(scale[output])
          if (mirror[output] != "")
            printf ", mirror = %s", lua_string(mirror[output])
          if (bitdepth[output] != "")
            printf ", bitdepth = %s", bitdepth[output]
          if (transform[output] != "")
            printf ", transform = %s", transform[output]
        }

        print " })"
      }
    }
  ' "$legacy_monitors" >"$tmp"; then
    mv "$tmp" "$target_monitors"
    return 0
  fi

  rm -f "$tmp"
  return 1
}

convert_workspaces() {
  tmp="$target_workspaces_tmp"

  if awk '
    function lua_string(value, escaped) {
      escaped = value
      gsub(/\\/, "\\\\", escaped)
      gsub(/"/, "\\\"", escaped)
      return "\"" escaped "\""
    }

    /^[[:space:]]*workspace[[:space:]]*=/ {
      line = $0
      sub(/^[[:space:]]*workspace[[:space:]]*=[[:space:]]*/, "", line)
      fields_count = split(line, fields, ",")
      workspace = fields[1]
      monitor = ""
      is_default = "false"

      for (i = 2; i <= fields_count; i++) {
        if (fields[i] ~ /^monitor:/) {
          monitor = fields[i]
          sub(/^monitor:/, "", monitor)
        } else if (fields[i] == "default:true") {
          is_default = "true"
        }
      }

      printf "hl.workspace_rule({ workspace = %s", lua_string(workspace)
      if (monitor != "")
        printf ", monitor = %s", lua_string(monitor)
      printf ", default = %s })\n", is_default
      count++
    }

    END {
      if (count == 0)
        exit 2
    }
  ' "$legacy_workspaces" >"$tmp"; then
    {
      printf "%s\n" "-- Generated by nwg-displays-lua. Do not edit manually."
      cat "$tmp"
    } >"$tmp.with-header"
    mv "$tmp.with-header" "$target_workspaces"
    rm -f "$tmp"
    return 0
  fi

  rm -f "$tmp" "$tmp.with-header"
  return 1
}

sync_lua() {
  current_fingerprint="$(fingerprint)"
  [ "$current_fingerprint" = "$last_fingerprint" ] && return 0
  last_fingerprint="$current_fingerprint"

  changed=false
  convert_monitors && changed=true
  convert_workspaces && changed=true
  if [ "$changed" = true ]; then
    hyprctl reload >/dev/null 2>&1 || true
  fi
}

last_fingerprint="$(fingerprint)"
@NWG_DISPLAYS@/bin/nwg-displays \
  --monitors_path "$legacy_monitors" \
  --workspaces_path "$legacy_workspaces" \
  --num_ws 5 &
nwg_pid=$!

while kill -0 "$nwg_pid" 2>/dev/null; do
  sync_lua
  sleep 0.2
done

status=0
wait "$nwg_pid" || status=$?
sync_lua
exit "$status"
