background {
  monitor =
  color = rgba(000000ff)
}

input-field {
  monitor =
  size = 280, 42
  position = 0, -40
  halign = center
  valign = center
  outline_thickness = 1
  dots_size = 0.22
  dots_spacing = 0.2
  outer_color = rgba(2f8cffcc)
  inner_color = rgba(050505ee)
  font_color = rgba(f5f5f5ff)
  font_family = JetBrainsMono Nerd Font
  placeholder_text = <span foreground="##b7c3d0">Password</span>
  check_color = rgba(2f8cffcc)
  fail_color = rgba(f05a5acc)
}

label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  color = rgba(f5f5f5ff)
  font_size = 42
  font_family = JetBrainsMono Nerd Font
  position = 0, 60
  halign = center
  valign = center
}
