auth {
  fingerprint {
    enabled = true
    ready_message = Scan fingerprint or enter password
    present_message = Scanning fingerprint
    retry_delay = 250
  }
}

background {
  monitor =
  path = @WALLPAPER@
  blur_passes = 2
  blur_size = 4
  brightness = 0.45
}

input-field {
  monitor =
  size = 280, 42
  position = 0, -40
  halign = center
  valign = center
  outline_thickness = 1
  dots_size = 0.22
  dots_spacing = 0.2
  outer_color = rgba(@ACCENT_BARE@cc)
  inner_color = rgba(050505ee)
  font_color = rgba(@FOREGROUND_BARE@ff)
  font_family = @FONT_MONO@
  placeholder_text = <span foreground="##@SUBTEXT_BARE@">Password or fingerprint</span>
  check_color = rgba(@ACCENT_BARE@cc)
  fail_color = rgba(@DANGER_BARE@cc)
}

label {
  monitor =
  text = cmd[update:1000] date +"%H:%M"
  color = rgba(@FOREGROUND_BARE@ff)
  font_size = 42
  font_family = @FONT_MONO@
  position = 0, 78
  halign = center
  valign = center
}

label {
  monitor =
  text = cmd[update:60000] date +"%A, %d %B"
  color = rgba(@TEXT_BARE@ee)
  font_size = 14
  font_family = @FONT_MONO@
  position = 0, 34
  halign = center
  valign = center
}
